### ISSUE TITLE
Multiline text overlaps

### ISSUE THREAD

**Issue by Jazzinghen** [sadolit/textractor-websocket-webui#1]
When hooking sentences that are longer than one line the lines overlap, making it almost impossible to read them.
This is an example:
![image](https://user-images.githubusercontent.com/230921/95229477-945abf80-083b-11eb-83f6-3c6638c40c84.png)
I tried to use the HTML inspector to check the CSS and it seems like there are two conflicting CSS `body` rules:
`line-height` is set both to `1.5` and `24px` for the entire `body` in file `2.f8bcac56.chunk.css`

**Comment by sadolit** [comment]
Merged.
